package com.coeus.eTap_app.enums;

public enum Category {
    ADMINISTRATION,
    LEGAL_SERVICES,
    COMPUTING_ICT,
    TRANSPORT,
    CUSTOMER_SERVICES,
    ENGINEERING,
    SOCIAL_WORK,
    FINANCIAL_SERVICES,
    SCIENCE,
    HEALTHCARE_SERVICES,
    PROPERTY_SERVICES,
    CONSTRUCTION_SERVICES,
    ANIMAL_SERVICES,
    EDUCATION,
    SECURITY_SERVICES,
    TOURISM,
    PRODUCTON,
    MEDIA_SERVICES,
    DESGINAL_SERVICES,
    OTHER
}
